name: Initial_Steps
description: Common initial steps for all workflows, with optional dependency installation.

inputs:
  install-dependencies: # Options: "all", "install", "none"
    description: "Whether to install dependencies"
    required: false
    default: "all"

runs:
  using: "composite"
  steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f086349bfa2bd1361f7909c78558e816508cdc10
      with:
        egress-policy: audit

    - name: Install glibc in Alpine to add multi-arch support
      shell: sh
      run: apk add --no-cache gcompat libc6-compat

    - name: Install dependencies to install contracts
      shell: sh
      if: ${{ inputs.install-dependencies == 'install' || inputs.install-dependencies == 'all' }}
      run: apk add --no-cache python3 py3-pip make g++

    - name: Install dependencies to create ENV file
      shell: sh
      if: ${{ inputs.install-dependencies == 'all' }}
      run: apk add --no-cache curl jq
