/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./Interfaces";
export type { interfaces };
export type { Burnable } from "./Burnable";
export type { CashIn } from "./CashIn";
export type { Deletable } from "./Deletable";
export type { Freezable } from "./Freezable";
export type { Pausable } from "./Pausable";
export type { Rescatable } from "./Rescatable";
export type { Reserve } from "./Reserve";
export type { Roles } from "./Roles";
export type { SupplierAdmin } from "./SupplierAdmin";
export type { TokenOwner } from "./TokenOwner";
export type { Wipeable } from "./Wipeable";
