/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./Interfaces";
export type { interfaces };
export type { Burnable } from "./Burnable";
export type { Mintable } from "./Mintable";
export type { Rescatable } from "./Rescatable";
export type { SupplierAdmin } from "./SupplierAdmin";
export type { TokenOwner } from "./TokenOwner";
export type { Wipeable } from "./Wipeable";
