/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMintable } from "./IMintable";
export type { IRescatable } from "./IRescatable";
export type { ISupplierAdmin } from "./ISupplierAdmin";
export type { IWipeable } from "./IWipeable";
export type { Mintable } from "./Mintable";
export type { Rescatable } from "./Rescatable";
export type { SupplierAdmin } from "./SupplierAdmin";
export type { Wipeable } from "./Wipeable";
