/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ReserveInterface extends utils.Interface {
  functions: {
    "updateReserve(address)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "updateReserve"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "updateReserve",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "updateReserve",
    data: BytesLike
  ): Result;

  events: {
    "ReserveAddressChanged(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ReserveAddressChanged"): EventFragment;
}

export interface ReserveAddressChangedEventObject {
  previousAddress: string;
  newAddress: string;
}
export type ReserveAddressChangedEvent = TypedEvent<
  [string, string],
  ReserveAddressChangedEventObject
>;

export type ReserveAddressChangedEventFilter =
  TypedEventFilter<ReserveAddressChangedEvent>;

export interface Reserve extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ReserveInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    updateReserve(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  updateReserve(
    newAddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    updateReserve(
      newAddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ReserveAddressChanged(address,address)"(
      previousAddress?: null,
      newAddress?: null
    ): ReserveAddressChangedEventFilter;
    ReserveAddressChanged(
      previousAddress?: null,
      newAddress?: null
    ): ReserveAddressChangedEventFilter;
  };

  estimateGas: {
    updateReserve(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    updateReserve(
      newAddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
