"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IAccessControlUpgradeable__factory = exports.AccessControlUpgradeable__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AccessControlUpgradeable__factory_1 = require("./AccessControlUpgradeable__factory");
Object.defineProperty(exports, "AccessControlUpgradeable__factory", { enumerable: true, get: function () { return AccessControlUpgradeable__factory_1.AccessControlUpgradeable__factory; } });
var IAccessControlUpgradeable__factory_1 = require("./IAccessControlUpgradeable__factory");
Object.defineProperty(exports, "IAccessControlUpgradeable__factory", { enumerable: true, get: function () { return IAccessControlUpgradeable__factory_1.IAccessControlUpgradeable__factory; } });
