/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IStableCoinFactory__factory } from "./IStableCoinFactory__factory";
export { StableCoinFactory__factory } from "./StableCoinFactory__factory";
