"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Wipeable__factory = exports.SupplierAdmin__factory = exports.Rescatable__factory = exports.Mintable__factory = exports.IWipeable__factory = exports.ISupplierAdmin__factory = exports.IRescatable__factory = exports.IMintable__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IMintable__factory_1 = require("./IMintable__factory");
Object.defineProperty(exports, "IMintable__factory", { enumerable: true, get: function () { return IMintable__factory_1.IMintable__factory; } });
var IRescatable__factory_1 = require("./IRescatable__factory");
Object.defineProperty(exports, "IRescatable__factory", { enumerable: true, get: function () { return IRescatable__factory_1.IRescatable__factory; } });
var ISupplierAdmin__factory_1 = require("./ISupplierAdmin__factory");
Object.defineProperty(exports, "ISupplierAdmin__factory", { enumerable: true, get: function () { return ISupplierAdmin__factory_1.ISupplierAdmin__factory; } });
var IWipeable__factory_1 = require("./IWipeable__factory");
Object.defineProperty(exports, "IWipeable__factory", { enumerable: true, get: function () { return IWipeable__factory_1.IWipeable__factory; } });
var Mintable__factory_1 = require("./Mintable__factory");
Object.defineProperty(exports, "Mintable__factory", { enumerable: true, get: function () { return Mintable__factory_1.Mintable__factory; } });
var Rescatable__factory_1 = require("./Rescatable__factory");
Object.defineProperty(exports, "Rescatable__factory", { enumerable: true, get: function () { return Rescatable__factory_1.Rescatable__factory; } });
var SupplierAdmin__factory_1 = require("./SupplierAdmin__factory");
Object.defineProperty(exports, "SupplierAdmin__factory", { enumerable: true, get: function () { return SupplierAdmin__factory_1.SupplierAdmin__factory; } });
var Wipeable__factory_1 = require("./Wipeable__factory");
Object.defineProperty(exports, "Wipeable__factory", { enumerable: true, get: function () { return Wipeable__factory_1.Wipeable__factory; } });
