/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IWipeable,
  IWipeableInterface,
} from "../../../contracts/extensions/IWipeable";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "wiper",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "amount",
        type: "uint32",
      },
    ],
    name: "TokensWiped",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        internalType: "uint32",
        name: "amount",
        type: "uint32",
      },
    ],
    name: "wipe",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IWipeable__factory {
  static readonly abi = _abi;
  static createInterface(): IWipeableInterface {
    return new utils.Interface(_abi) as IWipeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IWipeable {
    return new Contract(address, _abi, signerOrProvider) as IWipeable;
  }
}
