version: '3.9'

services:
  backend:
    build:
      context: ..  # Set build context to the parent directory
      dockerfile: backend/Dockerfile  # Dockerfile is inside the backend folder
      target: development
    container_name: ${CONTAINER_BACK_NAME}
    image: multisig-back:latest
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules  # Ensure node_modules is not overridden
      - log:/var/lib/logs
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    networks:
      - default-network
    environment:
      - NODE_ENV=development
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - ${CONTAINER_DB_NAME}
    command: npx nest start --watch

  db:
    image: postgres:14.11-alpine3.19
    container_name: ${CONTAINER_DB_NAME}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - default-network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
  log:
    driver: local

networks:
  default-network:
    name: ${DOCKER_NETWORK_NAME}
