/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as htsPrecompile from "./hts-precompile";
export type { htsPrecompile };
export type { HTSTokenOwner } from "./HTSTokenOwner";
export type { HederaERC1967Proxy } from "./HederaERC1967Proxy";
export type { HederaERC20 } from "./HederaERC20";
export type { IHederaERC20 } from "./IHederaERC20";
