/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stableCoinFactorySol from "./StableCoinFactory.sol";
export type { stableCoinFactorySol };
import type * as extensions from "./extensions";
export type { extensions };
import type * as htsPrecompile from "./hts-precompile";
export type { htsPrecompile };
export type { HederaERC20 } from "./HederaERC20";
export type { HederaERC20Proxy } from "./HederaERC20Proxy";
export type { IHederaERC20 } from "./IHederaERC20";
export type { Roles } from "./Roles";
