/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IStableCoinFactory } from "./IStableCoinFactory";
export type { StableCoinFactory } from "./StableCoinFactory";
