export enum Roles {
	CASHIN_ROLE = 'CASH IN',
	BURN_ROLE = 'BURN',
	WIPE_ROLE = 'WIPE',
	RESCUE_ROLE = 'RESCUE',
	PAUSE_ROLE = 'PAUSE',
	FREEZE_ROLE = 'FREEZE',
	DELETE_ROLE = 'DELETE',
	DEFAULT_ADMIN_ROLE = 'ADMIN',
}
