"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IHederaTokenService__factory = exports.HederaTokenService__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var HederaTokenService__factory_1 = require("./HederaTokenService__factory");
Object.defineProperty(exports, "HederaTokenService__factory", { enumerable: true, get: function () { return HederaTokenService__factory_1.HederaTokenService__factory; } });
var IHederaTokenService__factory_1 = require("./IHederaTokenService__factory");
Object.defineProperty(exports, "IHederaTokenService__factory", { enumerable: true, get: function () { return IHederaTokenService__factory_1.IHederaTokenService__factory; } });
