/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IHederaERC20 } from "./IHederaERC20";
export type { IStableCoinFactory } from "./IStableCoinFactory";
