"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.TokenOwner__factory = exports.Roles__factory = exports.ITokenOwner__factory = exports.IHTSTokenOwner__factory = exports.IHederaERC20__factory = exports.HTSTokenOwner__factory = exports.IHederaTokenService__factory = exports.HederaTokenService__factory = exports.HederaERC20__factory = exports.HederaERC1967Proxy__factory = exports.Wipeable__factory = exports.SupplierAdmin__factory = exports.Rescatable__factory = exports.Mintable__factory = exports.IWipeable__factory = exports.ISupplierAdmin__factory = exports.IRescatable__factory = exports.IMintable__factory = exports.Proxy__factory = exports.ERC1967Upgrade__factory = exports.ERC1967Proxy__factory = exports.IBeacon__factory = exports.IERC1822Proxiable__factory = exports.IERC165Upgradeable__factory = exports.ERC165Upgradeable__factory = exports.ContextUpgradeable__factory = exports.IERC20Upgradeable__factory = exports.IERC20MetadataUpgradeable__factory = exports.IERC20PermitUpgradeable__factory = exports.ERC20Upgradeable__factory = exports.Initializable__factory = exports.IAccessControlUpgradeable__factory = exports.AccessControlUpgradeable__factory = exports.factories = void 0;
exports.factories = __importStar(require("./factories"));
var AccessControlUpgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/access/AccessControlUpgradeable__factory");
Object.defineProperty(exports, "AccessControlUpgradeable__factory", { enumerable: true, get: function () { return AccessControlUpgradeable__factory_1.AccessControlUpgradeable__factory; } });
var IAccessControlUpgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/access/IAccessControlUpgradeable__factory");
Object.defineProperty(exports, "IAccessControlUpgradeable__factory", { enumerable: true, get: function () { return IAccessControlUpgradeable__factory_1.IAccessControlUpgradeable__factory; } });
var Initializable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/proxy/utils/Initializable__factory");
Object.defineProperty(exports, "Initializable__factory", { enumerable: true, get: function () { return Initializable__factory_1.Initializable__factory; } });
var ERC20Upgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/token/ERC20/ERC20Upgradeable__factory");
Object.defineProperty(exports, "ERC20Upgradeable__factory", { enumerable: true, get: function () { return ERC20Upgradeable__factory_1.ERC20Upgradeable__factory; } });
var IERC20PermitUpgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/token/ERC20/extensions/draft-IERC20PermitUpgradeable.sol/IERC20PermitUpgradeable__factory");
Object.defineProperty(exports, "IERC20PermitUpgradeable__factory", { enumerable: true, get: function () { return IERC20PermitUpgradeable__factory_1.IERC20PermitUpgradeable__factory; } });
var IERC20MetadataUpgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/token/ERC20/extensions/IERC20MetadataUpgradeable__factory");
Object.defineProperty(exports, "IERC20MetadataUpgradeable__factory", { enumerable: true, get: function () { return IERC20MetadataUpgradeable__factory_1.IERC20MetadataUpgradeable__factory; } });
var IERC20Upgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable__factory");
Object.defineProperty(exports, "IERC20Upgradeable__factory", { enumerable: true, get: function () { return IERC20Upgradeable__factory_1.IERC20Upgradeable__factory; } });
var ContextUpgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/utils/ContextUpgradeable__factory");
Object.defineProperty(exports, "ContextUpgradeable__factory", { enumerable: true, get: function () { return ContextUpgradeable__factory_1.ContextUpgradeable__factory; } });
var ERC165Upgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/utils/introspection/ERC165Upgradeable__factory");
Object.defineProperty(exports, "ERC165Upgradeable__factory", { enumerable: true, get: function () { return ERC165Upgradeable__factory_1.ERC165Upgradeable__factory; } });
var IERC165Upgradeable__factory_1 = require("./factories/@openzeppelin/contracts-upgradeable/utils/introspection/IERC165Upgradeable__factory");
Object.defineProperty(exports, "IERC165Upgradeable__factory", { enumerable: true, get: function () { return IERC165Upgradeable__factory_1.IERC165Upgradeable__factory; } });
var IERC1822Proxiable__factory_1 = require("./factories/@openzeppelin/contracts/interfaces/draft-IERC1822.sol/IERC1822Proxiable__factory");
Object.defineProperty(exports, "IERC1822Proxiable__factory", { enumerable: true, get: function () { return IERC1822Proxiable__factory_1.IERC1822Proxiable__factory; } });
var IBeacon__factory_1 = require("./factories/@openzeppelin/contracts/proxy/beacon/IBeacon__factory");
Object.defineProperty(exports, "IBeacon__factory", { enumerable: true, get: function () { return IBeacon__factory_1.IBeacon__factory; } });
var ERC1967Proxy__factory_1 = require("./factories/@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy__factory");
Object.defineProperty(exports, "ERC1967Proxy__factory", { enumerable: true, get: function () { return ERC1967Proxy__factory_1.ERC1967Proxy__factory; } });
var ERC1967Upgrade__factory_1 = require("./factories/@openzeppelin/contracts/proxy/ERC1967/ERC1967Upgrade__factory");
Object.defineProperty(exports, "ERC1967Upgrade__factory", { enumerable: true, get: function () { return ERC1967Upgrade__factory_1.ERC1967Upgrade__factory; } });
var Proxy__factory_1 = require("./factories/@openzeppelin/contracts/proxy/Proxy__factory");
Object.defineProperty(exports, "Proxy__factory", { enumerable: true, get: function () { return Proxy__factory_1.Proxy__factory; } });
var IMintable__factory_1 = require("./factories/contracts/extensions/IMintable__factory");
Object.defineProperty(exports, "IMintable__factory", { enumerable: true, get: function () { return IMintable__factory_1.IMintable__factory; } });
var IRescatable__factory_1 = require("./factories/contracts/extensions/IRescatable__factory");
Object.defineProperty(exports, "IRescatable__factory", { enumerable: true, get: function () { return IRescatable__factory_1.IRescatable__factory; } });
var ISupplierAdmin__factory_1 = require("./factories/contracts/extensions/ISupplierAdmin__factory");
Object.defineProperty(exports, "ISupplierAdmin__factory", { enumerable: true, get: function () { return ISupplierAdmin__factory_1.ISupplierAdmin__factory; } });
var IWipeable__factory_1 = require("./factories/contracts/extensions/IWipeable__factory");
Object.defineProperty(exports, "IWipeable__factory", { enumerable: true, get: function () { return IWipeable__factory_1.IWipeable__factory; } });
var Mintable__factory_1 = require("./factories/contracts/extensions/Mintable__factory");
Object.defineProperty(exports, "Mintable__factory", { enumerable: true, get: function () { return Mintable__factory_1.Mintable__factory; } });
var Rescatable__factory_1 = require("./factories/contracts/extensions/Rescatable__factory");
Object.defineProperty(exports, "Rescatable__factory", { enumerable: true, get: function () { return Rescatable__factory_1.Rescatable__factory; } });
var SupplierAdmin__factory_1 = require("./factories/contracts/extensions/SupplierAdmin__factory");
Object.defineProperty(exports, "SupplierAdmin__factory", { enumerable: true, get: function () { return SupplierAdmin__factory_1.SupplierAdmin__factory; } });
var Wipeable__factory_1 = require("./factories/contracts/extensions/Wipeable__factory");
Object.defineProperty(exports, "Wipeable__factory", { enumerable: true, get: function () { return Wipeable__factory_1.Wipeable__factory; } });
var HederaERC1967Proxy__factory_1 = require("./factories/contracts/HederaERC1967Proxy__factory");
Object.defineProperty(exports, "HederaERC1967Proxy__factory", { enumerable: true, get: function () { return HederaERC1967Proxy__factory_1.HederaERC1967Proxy__factory; } });
var HederaERC20__factory_1 = require("./factories/contracts/HederaERC20__factory");
Object.defineProperty(exports, "HederaERC20__factory", { enumerable: true, get: function () { return HederaERC20__factory_1.HederaERC20__factory; } });
var HederaTokenService__factory_1 = require("./factories/contracts/hts-precompile/HederaTokenService__factory");
Object.defineProperty(exports, "HederaTokenService__factory", { enumerable: true, get: function () { return HederaTokenService__factory_1.HederaTokenService__factory; } });
var IHederaTokenService__factory_1 = require("./factories/contracts/hts-precompile/IHederaTokenService__factory");
Object.defineProperty(exports, "IHederaTokenService__factory", { enumerable: true, get: function () { return IHederaTokenService__factory_1.IHederaTokenService__factory; } });
var HTSTokenOwner__factory_1 = require("./factories/contracts/HTSTokenOwner__factory");
Object.defineProperty(exports, "HTSTokenOwner__factory", { enumerable: true, get: function () { return HTSTokenOwner__factory_1.HTSTokenOwner__factory; } });
var IHederaERC20__factory_1 = require("./factories/contracts/IHederaERC20__factory");
Object.defineProperty(exports, "IHederaERC20__factory", { enumerable: true, get: function () { return IHederaERC20__factory_1.IHederaERC20__factory; } });
var IHTSTokenOwner__factory_1 = require("./factories/contracts/IHTSTokenOwner__factory");
Object.defineProperty(exports, "IHTSTokenOwner__factory", { enumerable: true, get: function () { return IHTSTokenOwner__factory_1.IHTSTokenOwner__factory; } });
var ITokenOwner__factory_1 = require("./factories/contracts/ITokenOwner__factory");
Object.defineProperty(exports, "ITokenOwner__factory", { enumerable: true, get: function () { return ITokenOwner__factory_1.ITokenOwner__factory; } });
var Roles__factory_1 = require("./factories/contracts/Roles__factory");
Object.defineProperty(exports, "Roles__factory", { enumerable: true, get: function () { return Roles__factory_1.Roles__factory; } });
var TokenOwner__factory_1 = require("./factories/contracts/TokenOwner__factory");
Object.defineProperty(exports, "TokenOwner__factory", { enumerable: true, get: function () { return TokenOwner__factory_1.TokenOwner__factory; } });
