name: Install_And_Build
description: Install dependencies and build modules as needed

inputs:
  module:
    description: "The module that is going to be tested"
    required: true

runs:
  using: composite
  steps:
    - name: Install Dependencies
      shell: sh
      run: | 
        npm ci
        npm ci --workspaces

    - name: Build Contracts
      shell: sh
      run: npm run build --workspace=contracts

    - name: Build SDK
      if: ${{ inputs.module == 'sdk' || inputs.module == 'cli' || inputs.module == 'web' }}
      shell: sh
      run: npm run build --workspace=sdk

    - name: Build CLI
      if: ${{ inputs.module == 'cli' }}
      shell: sh
      run: npm run build --workspace=cli

    # - name: Build Web
    #   if: ${{ inputs.module == 'web' }}
    #   shell: sh
    #   run: npm run build
    #   working-directory: web
