name: Install_And_Build
description: Install dependencies and build modules as needed

inputs:
  module:
    description: "The module that is going to be tested"
    required: true

runs:
  using: composite
  steps:
    - name: Install Contracts
      shell: sh
      run: npm ci --ignore-scripts --workspace=contracts

    - name: Build Contracts
      shell: sh
      run: npm run compile:force --workspace=contracts

    - name: Install SDK
      if: ${{ inputs.module == 'sdk' }}
      shell: sh
      run: npm ci --workspace=sdk

    - name: Build SDK
      if: ${{ inputs.module == 'sdk' }}
      shell: sh
      run: npm run build --workspace=sdk

    - name: Install CLI
      if: ${{ inputs.module == 'cli' }}
      shell: sh
      run: npm ci --workspace=cli

    - name: Build CLI
      if: ${{ inputs.module == 'cli' }}
      shell: sh
      run: npm run build --workspace=cli

    - name: Install Web
      if: ${{ inputs.module == 'web' }}
      shell: sh
      run: npm ci --workspace=web

    # - name: Build Web
    #   if: ${{ inputs.module == 'web' }}
    #   shell: sh
    #   run: npm run build
    #   working-directory: web
