general:
  configPath: >-
    /home/javi/.nvm/versions/node/v16.15.1/lib/node_modules/hedera-stable-coin-cli/config/.hedera-stable-cli.yaml
  network: testnet
networks:
  - name: mainnet
    consensusNodes:
      - url: 35.231.208.148:50211
        nodeId: 0.0.3
      - url: 35.199.15.177:50211
        nodeId: 0.0.4
      - url: 35.225.201.195:50211
        nodeId: 0.0.5
      - url: 35.247.109.135:50211
        nodeId: 0.0.6
    mirrorNodeUrl: https://mainnet.mirrornode.hedera.com/
    chainId: 0
  - name: previewnet
    consensusNodes:
      - url: 35.231.208.148:50211
        nodeId: 0.0.3
      - url: 35.199.15.177:50211
        nodeId: 0.0.4
      - url: 35.225.201.195:50211
        nodeId: 0.0.5
      - url: 35.247.109.135:50211
        nodeId: 0.0.6
    mirrorNodeUrl: https://previewnet.mirrornode.hedera.com/
    chainId: 0
  - name: testnet
    consensusNodes:
      - url: 0.testnet.hedera.com:50211
        nodeId: 0.0.3
      - url: 1.testnet.hedera.com:50211
        nodeId: 0.0.4
      - url: 2.testnet.hedera.com:50211
        nodeId: 0.0.5
      - url: 3.testnet.hedera.com:50211
        nodeId: 0.0.6
    mirrorNodeUrl: https://testnet.mirrornode.hedera.com
    chainId: 0
accounts:
  - accountId: 0.0.29511696
    privateKey: >-
      302e020100300506032b6570042204207a8a25387a3c636cb980d1ba548ee5ee3cc8cda158e42dc7af53dcd81022d8be
    isECDA25519Type: true
    alias: Admin
