defaultNetwork: testnet
networks:
  - name: mainnet
    consensusNodes: []
    mirrorNodeUrl: https://mainnet.mirrornode.hedera.com/
  - name: previewnet
    consensusNodes: []
    mirrorNodeUrl: https://previewnet.mirrornode.hedera.com/
  - name: testnet
    consensusNodes: []
    mirrorNodeUrl: https://testnet.mirrornode.hedera.com
accounts:
  - accountId: 0.0.47809960
    privateKey: >-
      302e020100300506032b6570042204201713ea5a2dc0287b11a6f25a1137c0cad65fb5af52706076de9a9ec5a4b7f625
    network: testnet
    alias: SergiAccount
