name: CLI - Test
on: 
  workflow_dispatch:
  push:
    branches: [main]
defaults:
  run:
    working-directory: cli
jobs:
  test-node:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js TLS 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies Hashconnect
        run: npm install
        working-directory: hashconnect/lib
      - name: Build Hashconnect
        run: npm run build
        working-directory: hashconnect/lib
      - name: Install dependencies Contracts
        run: npm install
        working-directory: contracts
      - name: Install dependencies SDK
        run: npm install
        working-directory: sdk
      - name: Test
        uses: ArtiomTr/jest-coverage-report-action@v2.0.9
        with:
          working-directory: cli
          test-script: npm run test
        # run: npm run test
        # working-directory: sdk
