name: Publish

on:
  release:
    types:
      - published

jobs:
  contracts:
    runs-on: token-studio-linux-medium
    container:
      image: node:20.17.0-alpine3.20 # Using alpine for a smaller image
    permissions:
      contents: read

    steps:
      # * Initial steps
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Initial steps
        uses: ./.github/actions/initial-steps
        with:
          install-dependencies: "install"

      - name: Create file .npmrc
        run: |
          cat <<EOF > .npmrc
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          EOF
        working-directory: contracts

      - name: Change references to repo
        run: ./changeProyectsReferencesToRepo.sh

      - name: Install Contracts
        run: npm ci
        working-directory: contracts

      - name: Build Contracts
        run: npm run compile:force
        working-directory: contracts

      # # ! Only for local testing, DO NOT uncomment for production
      # - name: Set NPM registry to Verdaccio (local)
      #   run: npm config set registry http://localhost:4873

      - name: Publish contracts
        run: npm run publish:contracts --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  sdk:
    needs: contracts
    runs-on: token-studio-linux-medium
    container:
      image: node:20.17.0-alpine3.20 # Using alpine for a smaller image
    permissions:
      contents: read

    steps:
      # * Initial steps
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Initial steps
        uses: ./.github/actions/initial-steps
        with:
          install-dependencies: "none"

      - name: Create file .npmrc
        run: |
          cat <<EOF > .npmrc
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          EOF
        working-directory: sdk

      - name: Change references to repo
        run: ./changeProyectsReferencesToRepo.sh

      - name: Install SDK
        run: npm ci
        working-directory: sdk

      - name: Build SDK
        run: npm run build
        working-directory: sdk

      - name: Publish sdk package
        run: npm run publish:sdk --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  cli:
    needs: sdk
    runs-on: token-studio-linux-medium
    container:
      image: node:20.17.0-alpine3.20 # Using alpine for a smaller image
    permissions:
      contents: read

    steps:
      # * Initial steps
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29

      - name: Initial steps
        uses: ./.github/actions/initial-steps
        with:
          install-dependencies: "none"

      - name: Create file .npmrc
        run: |
          cat <<EOF > .npmrc
          //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          EOF
        working-directory: cli

      - name: Change references to repo
        run: ./changeProyectsReferencesToRepo.sh

      - name: Install CLI
        run: npm ci
        working-directory: cli

      - name: Build CLI
        run: npm run build
        working-directory: cli

      - name: Publish cli package
        run: npm run publish:cli --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
