name: Test Secrets
on:
  pull_request:
  push:
    branches: [main]
jobs:
 test-node:
    name: testing secrets    
    #runs-on: [ self-hosted, Linux, medium, ephemeral ]
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max-old-space-size=32768"
    permissions:
      contents: read
    
    steps:
      - name: Verify specific secrets are available
        run: |
          echo "Verifying specific secrets..."
          missing_secrets=false

          check_secret() {
            secret_name=$1
            secret_value=${!secret_name}

            if [ -z "$secret_value" ]; then
              echo "Error: $secret_name is not set."
              missing_secrets=true
            else
              echo "$secret_name is set."
            fi
          }

          check_secret API_ACCESS_TOKEN_1
          check_secret API_ACCESS_TOKEN_2
          check_secret CLIENT_PRIVATE_KEY_ECDSA
          check_secret CLIENT_PUBLIC_KEY_ECDSA
          check_secret CLIENT_EVM_ADDRESS_ECDSA
          check_secret CLIENT_ACCOUNT_ID_ECDSA
          check_secret CLIENT_PRIVATE_KEY_ED25519
          check_secret CLIENT_PUBLIC_KEY_ED25519
          check_secret CLIENT_EVM_ADDRESS_ED25519
          check_secret CLIENT_ACCOUNT_ID_ED25519
          check_secret CLIENT_PRIVATE_KEY_ED25519_2
          check_secret CLIENT_PUBLIC_KEY_ED25519_2
          check_secret CLIENT_EVM_ADDRESS_ED25519_2
          check_secret CLIENT_ACCOUNT_ID_ED25519_2

          if [ "$missing_secrets" = true ]; then
            exit 1
          else
            echo "All specified secrets are set."
          fi
        env:
          API_ACCESS_TOKEN_1: ${{ secrets.API_ACCESS_TOKEN_1 }}
          API_ACCESS_TOKEN_2: ${{ secrets.API_ACCESS_TOKEN_2 }}
          CLIENT_PRIVATE_KEY_ECDSA: ${{ secrets.CLIENT_PRIVATE_KEY_ECDSA }}
          CLIENT_PUBLIC_KEY_ECDSA: ${{ secrets.CLIENT_PUBLIC_KEY_ECDSA }}
          CLIENT_EVM_ADDRESS_ECDSA: ${{ secrets.CLIENT_EVM_ADDRESS_ECDSA }}
          CLIENT_ACCOUNT_ID_ECDSA: ${{ secrets.CLIENT_ACCOUNT_ID_ECDSA }}
          CLIENT_PRIVATE_KEY_ED25519: ${{ secrets.CLIENT_PRIVATE_KEY_ED25519 }}
          CLIENT_PUBLIC_KEY_ED25519: ${{ secrets.CLIENT_PUBLIC_KEY_ED25519 }}
          CLIENT_EVM_ADDRESS_ED25519: ${{ secrets.CLIENT_EVM_ADDRESS_ED25519 }}
          CLIENT_ACCOUNT_ID_ED25519: ${{ secrets.CLIENT_ACCOUNT_ID_ED25519 }}
          CLIENT_PRIVATE_KEY_ED25519_2: ${{ secrets.CLIENT_PRIVATE_KEY_ED25519_2 }}
          CLIENT_PUBLIC_KEY_ED25519_2: ${{ secrets.CLIENT_PUBLIC_KEY_ED25519_2 }}
          CLIENT_EVM_ADDRESS_ED25519_2: ${{ secrets.CLIENT_EVM_ADDRESS_ED25519_2 }}
          CLIENT_ACCOUNT_ID_ED25519_2: ${{ secrets.CLIENT_ACCOUNT_ID_ED25519_2 }}
